### ISSUE TITLE
[BUG] iOS Display images

### ISSUE THREAD

**Issue by irodeanu** [Luehang/react-native-smart-gallery#14]
**To Do First**
- [*] Did you try latest release?
- [*] Did you look for existing matching issues?

**Software Package Version:**
1.1.3

**Describe the bug**
After the last update on iOS no longer displays the images. Neither example works.

**Version (please complete the following information):**
 - Device:  iPhoneX
 - iOS: 13
 - react-native: 0.61.5
 - react:16.9.0

**Additional context**
I guess it's related to `react-native-image-transformer` where the `source from this.state` is undefined in render

**Comment by Luehang** [comment]
Hi,

Thanks for letting me know.  You can update the package to latest to fix the issue.

```bash
$ npm install --save react-native-smart-gallery@latest
```

or

```bash
$ yarn add react-native-smart-gallery@latest
```

**Comment by irodeanu** [comment]
Now it works, thank you very much @Luehang
